const COUNTRIES = {
	FETCH: 'COUNTRIES_FETCH',
	FETCH_SUCCESS: 'COUNTRIES_FETCH_SUCCESS',
	FETCH_FAIL: 'COUNTRIES_FETCH_FAIL'
};

const SELECTED_COUNTRIES = {
	SET: 'SELECTED_COUNTRIES_SET',
	REMOVE_ITEM: 'SELECTED_COUNTRIES_REMOVE_ITEM',
	RESET: 'SELECTED_COUNTRIES_RESET'
};

export { COUNTRIES, SELECTED_COUNTRIES };
